export const serverData = [
    {"key":"Healthcare",
        "count":12540,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams",
            "A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Public Health",
        "count":8250,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams",
            "A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Descrimination",
        "count":5635,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams",
            "A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"North America",
        "count":5115,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams",
            "A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Education Level",
        "count":2386,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams",
            "A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Risk Factor",
        "count":1420,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams",
            "A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Hidden Label 1",
        "count":860,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams",
            "A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Hidden Label 2",
        "count":820,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams",
            "A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Hidden Label 2",
        "count":820,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams Nancy Kassam-Adams, Other Contributor",
            "Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Hidden Label 3",
        "count":600,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Hidden Label 4",
        "count":300,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams"]},
    {"key":"Hidden Label 5",
        "count":300,
        "documents":["A cost-effectiveness analysis of three staffing models for the delivery of low-risk prenatal care. 2015, The medical questions, Vol. 7",
            "Nancy Kassam-Adams, Other Contributor Some other artifact title 6/21/2014 Nancy Kassam-Adams"]}
]